apiVersion: batch/v1
kind: Job
metadata:
  name: countrybank-job
spec:
  template:
    spec:
      containers:
      - name: countrybank-job
        image: yash5090/countrybank:latest
        ports:
        - containerPort: 8000
      restartPolicy: OnFailure
